// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumberDecompostion(ctx context.Context, in *PrimeNumberDecompostionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompostionClient, error)
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error)
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error)
	PerfectNumber(ctx context.Context, in *PerfectNumberRequest, opts ...grpc.CallOption) (CalculatorService_PerfectNumberClient, error)
	TotalNumber(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_TotalNumberClient, error)
	FindMinimum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMinimumClient, error)
	SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecompostion(ctx context.Context, in *PrimeNumberDecompostionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompostionClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumberDecompostion", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompostionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompostionClient interface {
	Recv() (*PrimeNumberDecompostionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompostionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompostionClient) Recv() (*PrimeNumberDecompostionResponse, error) {
	m := new(PrimeNumberDecompostionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], "/calculator.CalculatorService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceComputeAverageClient{stream}
	return x, nil
}

type CalculatorService_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type calculatorServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], "/calculator.CalculatorService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceFindMaximumClient{stream}
	return x, nil
}

type CalculatorService_FindMaximumClient interface {
	Send(*FindMaximumRequest) error
	Recv() (*FindMaximumResponse, error)
	grpc.ClientStream
}

type calculatorServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceFindMaximumClient) Send(m *FindMaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumClient) Recv() (*FindMaximumResponse, error) {
	m := new(FindMaximumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) PerfectNumber(ctx context.Context, in *PerfectNumberRequest, opts ...grpc.CallOption) (CalculatorService_PerfectNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[3], "/calculator.CalculatorService/PerfectNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePerfectNumberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PerfectNumberClient interface {
	Recv() (*PerfectNumberResponse, error)
	grpc.ClientStream
}

type calculatorServicePerfectNumberClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePerfectNumberClient) Recv() (*PerfectNumberResponse, error) {
	m := new(PerfectNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) TotalNumber(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_TotalNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[4], "/calculator.CalculatorService/TotalNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceTotalNumberClient{stream}
	return x, nil
}

type CalculatorService_TotalNumberClient interface {
	Send(*TotalNumberRequest) error
	CloseAndRecv() (*TotalNumberResponse, error)
	grpc.ClientStream
}

type calculatorServiceTotalNumberClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceTotalNumberClient) Send(m *TotalNumberRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceTotalNumberClient) CloseAndRecv() (*TotalNumberResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TotalNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) FindMinimum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMinimumClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[5], "/calculator.CalculatorService/FindMinimum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceFindMinimumClient{stream}
	return x, nil
}

type CalculatorService_FindMinimumClient interface {
	Send(*FindMinimumRequest) error
	Recv() (*FindMinimumResponse, error)
	grpc.ClientStream
}

type calculatorServiceFindMinimumClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceFindMinimumClient) Send(m *FindMinimumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceFindMinimumClient) Recv() (*FindMinimumResponse, error) {
	m := new(FindMinimumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/SquareRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumberDecompostion(*PrimeNumberDecompostionRequest, CalculatorService_PrimeNumberDecompostionServer) error
	ComputeAverage(CalculatorService_ComputeAverageServer) error
	FindMaximum(CalculatorService_FindMaximumServer) error
	PerfectNumber(*PerfectNumberRequest, CalculatorService_PerfectNumberServer) error
	TotalNumber(CalculatorService_TotalNumberServer) error
	FindMinimum(CalculatorService_FindMinimumServer) error
	SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (UnimplementedCalculatorServiceServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServiceServer) PrimeNumberDecompostion(*PrimeNumberDecompostionRequest, CalculatorService_PrimeNumberDecompostionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecompostion not implemented")
}
func (UnimplementedCalculatorServiceServer) ComputeAverage(CalculatorService_ComputeAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}
func (UnimplementedCalculatorServiceServer) FindMaximum(CalculatorService_FindMaximumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximum not implemented")
}
func (UnimplementedCalculatorServiceServer) PerfectNumber(*PerfectNumberRequest, CalculatorService_PerfectNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method PerfectNumber not implemented")
}
func (UnimplementedCalculatorServiceServer) TotalNumber(CalculatorService_TotalNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method TotalNumber not implemented")
}
func (UnimplementedCalculatorServiceServer) FindMinimum(CalculatorService_FindMinimumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMinimum not implemented")
}
func (UnimplementedCalculatorServiceServer) SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}
func (UnimplementedCalculatorServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecompostion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompostionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecompostion(m, &calculatorServicePrimeNumberDecompostionServer{stream})
}

type CalculatorService_PrimeNumberDecompostionServer interface {
	Send(*PrimeNumberDecompostionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompostionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompostionServer) Send(m *PrimeNumberDecompostionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).ComputeAverage(&calculatorServiceComputeAverageServer{stream})
}

type CalculatorService_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type calculatorServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).FindMaximum(&calculatorServiceFindMaximumServer{stream})
}

type CalculatorService_FindMaximumServer interface {
	Send(*FindMaximumResponse) error
	Recv() (*FindMaximumRequest, error)
	grpc.ServerStream
}

type calculatorServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceFindMaximumServer) Send(m *FindMaximumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumServer) Recv() (*FindMaximumRequest, error) {
	m := new(FindMaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_PerfectNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PerfectNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PerfectNumber(m, &calculatorServicePerfectNumberServer{stream})
}

type CalculatorService_PerfectNumberServer interface {
	Send(*PerfectNumberResponse) error
	grpc.ServerStream
}

type calculatorServicePerfectNumberServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePerfectNumberServer) Send(m *PerfectNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_TotalNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).TotalNumber(&calculatorServiceTotalNumberServer{stream})
}

type CalculatorService_TotalNumberServer interface {
	SendAndClose(*TotalNumberResponse) error
	Recv() (*TotalNumberRequest, error)
	grpc.ServerStream
}

type calculatorServiceTotalNumberServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceTotalNumberServer) SendAndClose(m *TotalNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceTotalNumberServer) Recv() (*TotalNumberRequest, error) {
	m := new(TotalNumberRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_FindMinimum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).FindMinimum(&calculatorServiceFindMinimumServer{stream})
}

type CalculatorService_FindMinimumServer interface {
	Send(*FindMinimumResponse) error
	Recv() (*FindMinimumRequest, error)
	grpc.ServerStream
}

type calculatorServiceFindMinimumServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceFindMinimumServer) Send(m *FindMinimumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceFindMinimumServer) Recv() (*FindMinimumRequest, error) {
	m := new(FindMinimumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/SquareRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
		{
			MethodName: "SquareRoot",
			Handler:    _CalculatorService_SquareRoot_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _CalculatorService_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecompostion",
			Handler:       _CalculatorService_PrimeNumberDecompostion_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculatorService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculatorService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PerfectNumber",
			Handler:       _CalculatorService_PerfectNumber_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TotalNumber",
			Handler:       _CalculatorService_TotalNumber_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMinimum",
			Handler:       _CalculatorService_FindMinimum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculatorpb/calculator.proto",
}
